### ISSUE TITLE
Template names are not readable by default on Mac OS X

### ISSUE THREAD

**Issue by mcollina** [platformatic/meraki#170]
<img width="994" alt="Screenshot 2024-01-24 at 17 37 46" src="https://github.com/platformatic/meraki/assets/52195/310efa8e-516e-416c-9668-514115ff9391">

**Comment by Fmusso94** [comment]
@tonysnowboardunderthebridge we can actually solve this with the following adjustments:

**1)** Reduce the number of results shown per row. Instead of showing 4, we are going to show just 3 per row (this will allow us to show cards with quite long titles)
**2)** Reduce the title size. Reduce from 20pt to 18pt 

You can find the design on Figma. Here is a quick preview: (_this adjustment can be applied also to the Marketplace cards_)
![Screenshot 2024-01-24 at 2 23 32 PM](https://github.com/platformatic/meraki/assets/78840283/95e5c69f-bf66-4939-a647-fbc5cf57bd5d)

CC: @marcopiraccini
