### ISSUE TITLE
do not allow to edit an app if it's not running latest Platformatic

### ISSUE THREAD

**Issue by mcollina** [platformatic/meraki#552]

**Comment by marcopiraccini** [comment]
We should also explain why the "edit" is blocked.  in some form.

**Comment by Fmusso94** [comment]
Sounds good to me. Besides disabling the button, the only addition we should make to the design is to state clearly that the Platformatic Version needs to be updated to edit an application. We should go for the following solution:

![Screenshot 2024-04-05 at 7 15 06 AM](https://github.com/platformatic/meraki/assets/78840283/63df1753-b7a1-46d9-8a81-ca5a237f040f)

CC: @marcopiraccini @mcollina

**Comment by marcopiraccini** [comment]
@mcollina just one point. Currently we don't know which version is running Platformatic until...it's running.  In other words, if an application has never started we don't know the version (which is actually the "last known version" really), which will be any version semver compatible with the dependency in `package.json`.  This is because we currently get the info of the version from the runtime APIs (which is OK becasue this will work also remotely).
I see three options here:
- We disable the button in the case we don't know the version
- When we click on "edit" we check the current ACTUAL installed version (with `npm ls` ) given that fact that if we edit the app it MUST be local.

**Comment by mcollina** [comment]
> We disable the button in the case we don't know the version

If the last known version was old, I would show the button. If we don't know it, we don't show the warning at all.

> When we click on "edit" we check the current ACTUAL installed version (with npm ls ) given that fact that if we edit the app it MUST be local.

The button __must__ be for local-only apps.

Note a `npm ls` might not be enough because yarn or pnpm would require different commands.

**Comment by tonysnowboardunderthebridge** [comment]
Hi @mcollina 

I'm closing this one because the described behavior (my last comment) it's already on meraki 1.0.1.

Reopen the issue if the solution doesn't match requirements.
