### ISSUE TITLE
If the install errors, update the "progress label accordingly"

### ISSUE THREAD

**Issue by mcollina** [platformatic/meraki#79]
<img width="1690" alt="Screenshot 2023-12-08 at 09 10 27" src="https://github.com/platformatic/meraki/assets/52195/74422e52-b36e-4bc1-b1d0-829be33654a6">

When the install fails, the label should say "Something went wrong, report this issue.". The "report this issue" should:

1. show an alert that says "the logs you are sending will be sanitized of any sensitive data, cancel or continue" (@Fmusso94 would need to come up with a design)
2. If continue is clicked the logs are sent.
3. Meraki goes back to ? page (to figure it out)
 
The logs should be sent to an API on one of our services

**Comment by tonysnowboardunderthebridge** [comment]
HI @mcollina , @Fmusso94 

I will go close this issue because on the new flow this scenario is coveder: 

1) When some error occurs, the following page is displayed to the user
<img width="598" alt="Schermata 2024-04-03 alle 14 50 11" src="https://github.com/platformatic/meraki/assets/25035977/862ad51b-1704-4833-a839-58802befcf39">

2) he/she can report the issue (once that the report api will be ready) copy the logs or dismiss.

if you agree with this solution, please close this issue

**Comment by mcollina** [comment]
Looks ok for now.
